discord:
    token: paste_token_here
    server_id: 'server_id_goes_here'
twitch:
    user: 'username'
    oauth: 'oauth:paste_token_here'
    channel: 'twitch_user_name'
    prefix: '!'  # defaults to !