bot:
    debug: False  # don't change this unless you have a good reason pls <3
    help_cmds: 
        - "help"
        - "cmds"
        - "commands"

bot_ctrl:
    off_cmd: "quit"

custom_responses:
    welcome_msg: "I'm back, baby!"
    no_privilege: "I can't do that, @{}"
    link_msg: "NSFW!!"

moderation:
    strike_1_timeout: 60
    strike_2_timeout: 600

sfx:
    hooks_timeout: 10 # Timeout period (seconds) between basic hooks cmds
    random_timeout: 0 # Same but for random sfx/folders